#!/usr/bin/env bash

set -e

if ! command -v ytt > /dev/null 2>&1; then
    echo "Please install ytt to run the pre-commit hook! https://carvel.dev/ytt/docs/v0.46.x/install/"
    exit 1
fi

ytt -f schema.yaml --data-values-schema-inspect --output openapi-v3 > ./docs/ytt-schema.yaml
